LANG = {
    "English": {
        "choose_farm": "Choose Your Farm",
        "hello": "Hello",
        "location": "Location",
        "did_irrigate": "Did you irrigate recently?",
        "yes": "Yes",
        "no": "No",
        "check_farm": "CHECK MY FARM",
        "farm_report": "Your Farm Report",
        "crop_health_scale": "Crop Health Scale",
        "fully_healthy": "Fully Healthy",
        "slight_stress": "Slight Stress",
        "moderate_stress": "Moderate Stress",
        "high_stress": "High Stress",
        "severe_wilted": "Severe / Wilted",
        "crop_health": "Crop Health Status",
        "no_irrigation_now": "No irrigation needed right now.",
        "irrigation_soon": "Irrigation recommended soon.",
        "irrigation_now": "Immediate irrigation required!",
        "msg_fully_healthy": "Your crop is in excellent condition.",
        "msg_slight_stress": "Minor stress. Keep an eye on your field.",
        "msg_moderate_stress": "Irrigation recommended soon.",
        "msg_high_stress": "Irrigate your crop soon!",
        "msg_severe_wilted": "Immediate irrigation required urgently!",
        "safe_delay": "Safe Delay Countdown",
        "safe_delay_caption": "How long can you safely wait before watering?",
        "hours": "hours",
        "hours_left": "hours left",
        "irrigate_now": "Irrigate RIGHT NOW!",
        "irrigate_within": "Irrigate within",
        "days_safe": "days safe to wait",
        "safe_to_wait": "safe to wait",
        "safe_about": "Safe for about",
        "days": "days",
        "crop": "Crop",
        "recent_irrigated": "Recently irrigated",
        "safe_delay_desc": "Based on crop type and current weather conditions, this is how long your crop can safely go without water.",
        "best_irrigation_time": "Best Time to Irrigate Today",
        "why": "Why?",
        "early_morning_evening": "🌅 Early Morning (5–7 AM) or 🌆 Evening (6–8 PM)",
        "very_hot_reason": "Very hot today — watering midday wastes water. Early or evening is best.",
        "avoid_midday": "❌ Avoid watering 10 AM – 4 PM (high evaporation)",
        "morning_time": "🌅 Morning (6–9 AM)",
        "moderate_heat_reason": "Moderate heat expected. Morning watering lets plants absorb before afternoon.",
        "avoid_afternoon": "❌ Avoid watering after 2 PM today",
        "anytime_morning": "🕐 Anytime — Morning preferred",
        "mild_weather_reason": "Mild weather today. You can water anytime, but morning is best habit.",
        "run_motor": "Run motor for about",
        "run_drip": "Run drip irrigation for about",
        "irrigate_for": "Irrigate for about",
        "minutes": "minutes",
        "irrigation_risk": "Irrigation Risk Level",
        "low_risk": "Low Risk",
        "moderate_risk": "Moderate Risk",
        "high_risk": "High Risk",
        "very_high_risk": "Very High Risk",
        "risk_safe": "Your crop is safe. No action needed.",
        "risk_watch": "Keep an eye on your field. Water soon.",
        "risk_plan": "Your crop needs water. Plan irrigation.",
        "risk_now": "Irrigate immediately! Crop is at serious risk.",
        "very_low": "Very Low",
        "low": "Low",
        "moderate": "Moderate",
        "high": "High",
        "very_high": "Very High",
        "rain_forecast_7days": "Rain Forecast — Last 7 Days",
        "rain_caption": "Based on actual NASA rainfall data from your farm's location.",
        "no_rain": "No rain",
        "very_little_rain": "Very little rain",
        "light_rain": "Light rain",
        "moderate_rain": "Moderate rain",
        "good_rain": "Good rain",
        "heavy_rain": "Heavy rain",
        "rain_good": "Good rainfall recently! You may be able to delay irrigation.",
        "rain_some": "Some rain received. Monitor your field before irrigating.",
        "rain_low": "Very little rain this week. Consider irrigating soon.",
        "water_stress_trend": "Water Stress Trend — Last 7 Days",
        "date": "Date",
        "water_stress_level": "IDI — Water Stress Level",
        "welcome_login": "Welcome! Enter your mobile number to continue.",
        "mobile_number": "Mobile Number",
        "mobile_placeholder": "10-digit number e.g. 9876543210",
        "valid_mobile": "Enter a valid 10-digit number.",
        "no_account": "No account found. Please create one →",
        "account_exists": "Account exists. Please login.",
        "create_account_title": "Create Your Account",
        "new_account_for": "New account for:",
        "signup_caption": "Fill in once — everything loads automatically every login.",
        "your_name": "Your Name",
        "name_placeholder": "e.g. Ramu",
        "your_farms": "Your Farms",
        "farm_caption": "You can add multiple farms. Each farm can have its own crop and water sources.",
        "how_many_farms": "How many farms do you have?",
        "save_start": "Save & Start →",
        "back_login": "Back to Login",
        "enter_place": "Enter Village, Mandal, District",
        "place_placeholder": "Example: Abedoddi, Jogulamba Gadwal, Telangana",
        "search_location": "Search Location",
        "location_found": "Location found",
        "try_location_more": "Try adding mandal/district/state name",
        "final_location": "Final Farm Location",
        "open_google_maps": "Open Location in Google Maps",
        "verify_map": "Open map, verify farm, then fine adjust below if needed.",
        "paste_coordinates": "Paste Exact Farm Coordinates",
        "copy_coordinates_help": "Google Maps → Right click farm → Copy coordinates → Paste below",
        "coord_placeholder": "Example: 15.32627, 76.78785",
        "set_coordinates": "Set Farm Coordinates",
        "coordinates_set": "Farm coordinates set successfully",
        "coord_format": "Use format: latitude, longitude",
        "edit_profile": "Edit My Profile",
        "save_changes_caption": "Changes are saved when you click Save Changes.",
        "name": "Name",
        "marked_delete": "marked for deletion",
        "undo": "Undo",
        "delete_farm": "Delete this farm",
        "keep_one_farm": "You must keep at least one farm.",
        "add_new_farm": "Add a New Farm",
        "new_farm_details": "New Farm Details",
        "save_changes": "Save Changes",
        "back_dashboard": "Back to Dashboard",
        "set_location": "Set Farm Location",
        "select_crop": "Select Crop",
        "water_sources": "Water Sources",
        "sign_out": "Sign Out",
        "login": "Login",
        "create_account": "Create Account",
        "farmer_advisory_system": "Farmer Advisory System",
        "crop_label": "Crop",
        "farm_area": "Farm Area (Acres)",
        "acres": "acres"
    },

    "Telugu": {
        "choose_farm": "మీ పొలం ఎంచుకోండి",
        "hello": "హలో",
        "location": "స్థానం",
        "did_irrigate": "ఇటీవల నీరు పెట్టారా?",
        "yes": "అవును",
        "no": "లేదు",
        "check_farm": "నా పొలం చూడండి",
        "farm_report": "మీ పొలం నివేదిక",
        "crop_health_scale": "పంట ఆరోగ్య స్థాయి",
        "fully_healthy": "పూర్తిగా ఆరోగ్యంగా",
        "slight_stress": "స్వల్ప ఒత్తిడి",
        "moderate_stress": "మధ్యస్థ ఒత్తిడి",
        "high_stress": "అధిక ఒత్తిడి",
        "severe_wilted": "తీవ్ర వాడిపోవడం",
        "crop_health": "పంట ఆరోగ్య స్థితి",
        "no_irrigation_now": "ఇప్పుడు నీరు అవసరం లేదు.",
        "irrigation_soon": "త్వరలో నీరు పెట్టాలి.",
        "irrigation_now": "తక్షణం నీరు పెట్టాలి!",
        "msg_fully_healthy": "మీ పంట చాలా మంచి స్థితిలో ఉంది.",
        "msg_slight_stress": "స్వల్ప ఒత్తిడి ఉంది. గమనించండి.",
        "msg_moderate_stress": "త్వరలో నీరు పెట్టడం మంచిది.",
        "msg_high_stress": "త్వరగా నీరు పెట్టండి.",
        "msg_severe_wilted": "తక్షణం నీరు పెట్టాలి!",
        "safe_delay": "సురక్షిత ఆలస్యం గణన",
        "safe_delay_caption": "నీరు పెట్టే ముందు ఎంతసేపు వేచి ఉండవచ్చు?",
        "hours": "గంటలు",
        "hours_left": "గంటలు మిగిలాయి",
        "irrigate_now": "ఇప్పుడే నీరు పెట్టండి!",
        "irrigate_within": "ఈలోపు నీరు పెట్టండి",
        "days_safe": "రోజులు సురక్షితం",
        "safe_to_wait": "వేచి ఉండవచ్చు",
        "safe_about": "సుమారు",
        "days": "రోజులు",
        "crop": "పంట",
        "recent_irrigated": "ఇటీవల నీరు పెట్టారా",
        "safe_delay_desc": "ప్రస్తుత వాతావరణం మరియు పంట ఆధారంగా నీరు లేకుండా ఎంతసేపు ఉండగలదో ఇది చూపిస్తుంది.",
        "best_irrigation_time": "ఈరోజు నీరు పెట్టడానికి మంచి సమయం",
        "why": "ఎందుకు?",
        "early_morning_evening": "🌅 తెల్లవారుజాము (5–7 AM) లేదా 🌆 సాయంత్రం (6–8 PM)",
        "very_hot_reason": "ఈరోజు చాలా వేడి ఉంది — మధ్యాహ్నం నీరు వృథా అవుతుంది.",
        "avoid_midday": "❌ 10 AM – 4 PM మధ్య నీరు పెట్టవద్దు",
        "morning_time": "🌅 ఉదయం (6–9 AM)",
        "moderate_heat_reason": "సాధారణ వేడి ఉంది. ఉదయం నీరు మంచిది.",
        "avoid_afternoon": "❌ ఈరోజు 2 PM తర్వాత నీరు పెట్టవద్దు",
        "anytime_morning": "🕐 ఎప్పుడైనా — ఉదయం ఉత్తమం",
        "mild_weather_reason": "వాతావరణం సాఫీగా ఉంది. ఉదయం నీరు పెట్టడం మంచిది.",
        "run_motor": "మోటార్ నడపండి సుమారు",
        "run_drip": "డ్రిప్ నడపండి సుమారు",
        "irrigate_for": "నీరు పెట్టండి సుమారు",
        "minutes": "నిమిషాలు",
        "irrigation_risk": "నీటి ప్రమాద స్థాయి",
        "low_risk": "తక్కువ ప్రమాదం",
        "moderate_risk": "మధ్యస్థ ప్రమాదం",
        "high_risk": "అధిక ప్రమాదం",
        "very_high_risk": "చాలా అధిక ప్రమాదం",
        "risk_safe": "మీ పంట సురక్షితం.",
        "risk_watch": "పంటను గమనించండి. త్వరలో నీరు పెట్టండి.",
        "risk_plan": "నీరు అవసరం. ప్లాన్ చేయండి.",
        "risk_now": "తక్షణం నీరు పెట్టండి!",
        "very_low": "చాలా తక్కువ",
        "low": "తక్కువ",
        "moderate": "మధ్యస్థ",
        "high": "అధికం",
        "very_high": "చాలా అధికం",
        "rain_forecast_7days": "గత 7 రోజుల వర్ష సూచన",
        "rain_caption": "మీ పొలం ప్రదేశానికి NASA వర్ష డేటా ఆధారంగా.",
        "no_rain": "వర్షం లేదు",
        "very_little_rain": "చాలా తక్కువ వర్షం",
        "light_rain": "తేలికపాటి వర్షం",
        "moderate_rain": "మధ్యస్థ వర్షం",
        "good_rain": "మంచి వర్షం",
        "heavy_rain": "భారీ వర్షం",
        "rain_good": "ఇటీవల మంచి వర్షం పడింది. నీరు ఆలస్యం చేయవచ్చు.",
        "rain_some": "కొంత వర్షం వచ్చింది. ముందుగా పొలం చూడండి.",
        "rain_low": "ఈ వారం తక్కువ వర్షం. త్వరలో నీరు పెట్టండి.",
        "water_stress_trend": "గత 7 రోజుల నీటి ఒత్తిడి ధోరణి",
        "date": "తేదీ",
        "water_stress_level": "నీటి ఒత్తిడి స్థాయి",
        "welcome_login": "స్వాగతం! కొనసాగడానికి మొబైల్ నంబర్ ఇవ్వండి.",
        "mobile_placeholder": "10 అంకెల సంఖ్య",
        "valid_mobile": "సరైన 10 అంకెల మొబైల్ నంబర్ ఇవ్వండి.",
        "no_account": "ఖాతా లేదు. కొత్తది సృష్టించండి →",
        "account_exists": "ఖాతా ఉంది. లాగిన్ చేయండి.",
        "create_account_title": "మీ ఖాతా సృష్టించండి",
        "new_account_for": "కొత్త ఖాతా:",
        "signup_caption": "ఒకసారి నింపండి — ప్రతి లాగిన్‌లో ఆటోమేటిక్‌గా లోడ్ అవుతుంది.",
        "your_name": "మీ పేరు",
        "name_placeholder": "ఉదా: రాము",
        "your_farms": "మీ పొలాలు",
        "farm_caption": "మీరు అనేక పొలాలు జోడించవచ్చు.",
        "how_many_farms": "మీకు ఎన్ని పొలాలు ఉన్నాయి?",
        "save_start": "సేవ్ చేసి ప్రారంభించండి →",
        "back_login": "లాగిన్‌కు తిరిగి వెళ్ళండి",
        "enter_place": "గ్రామం, మండలం, జిల్లా నమోదు చేయండి",
        "place_placeholder": "ఉదా: అబేదొడ్డి, జోగులాంబ గద్వాల్, తెలంగాణ",
        "search_location": "స్థానం వెతకండి",
        "location_found": "స్థానం కనుగొనబడింది",
        "try_location_more": "మండలం / జిల్లా / రాష్ట్రం జోడించండి",
        "final_location": "చివరి పొలం స్థానం",
        "open_google_maps": "Google Maps లో స్థానం తెరవండి",
        "verify_map": "మ్యాప్‌లో పరిశీలించి అవసరమైతే కింద సరిచేయండి.",
        "paste_coordinates": "ఖచ్చితమైన పొలం కోఆర్డినేట్లు పెట్టండి",
        "copy_coordinates_help": "Google Maps → పొలంపై రైట్ క్లిక్ → కోఆర్డినేట్లు కాపీ చేసి ఇక్కడ పెట్టండి",
        "coord_placeholder": "ఉదా: 15.32627, 76.78785",
        "set_coordinates": "పొలం కోఆర్డినేట్లు అమర్చండి",
        "coordinates_set": "పొలం కోఆర్డినేట్లు విజయవంతంగా అమర్చబడ్డాయి",
        "coord_format": "ఈ విధంగా ఇవ్వండి: latitude, longitude",
        "edit_profile": "నా ప్రొఫైల్ సవరించండి",
        "save_changes_caption": "Save Changes నొక్కినప్పుడు మార్పులు సేవ్ అవుతాయి.",
        "name": "పేరు",
        "marked_delete": "తొలగించడానికి గుర్తించబడింది",
        "undo": "రద్దు",
        "delete_farm": "ఈ పొలం తొలగించండి",
        "keep_one_farm": "కనీసం ఒక పొలం ఉంచాలి.",
        "add_new_farm": "కొత్త పొలం జోడించండి",
        "new_farm_details": "కొత్త పొలం వివరాలు",
        "save_changes": "మార్పులు సేవ్ చేయండి",
        "back_dashboard": "డాష్‌బోర్డ్‌కు తిరిగి వెళ్ళండి",
        "set_location": "పొలం స్థానం సెట్ చేయండి",
        "select_crop": "పంటను ఎంచుకోండి",
        "water_sources": "నీటి వనరులు",
        "sign_out": "లాగ్ అవుట్",
        "login": "లాగిన్",
        "create_account": "ఖాతా సృష్టించండి",
        "farmer_advisory_system": "రైతు సలహా వ్యవస్థ",
        "crop_label": "పంట",
        "farm_area": "పొలం విస్తీర్ణం (ఎకరాలు)",
        "acres": "ఎకరాలు"
    },

    "Kannada": {
        "choose_farm": "ನಿಮ್ಮ ಹೊಲ ಆಯ್ಕೆಮಾಡಿ",
        "hello": "ನಮಸ್ಕಾರ",
        "location": "ಸ್ಥಳ",
        "did_irrigate": "ಇತ್ತೀಚೆಗೆ ನೀರಾವರಿ ಮಾಡಿದ್ದೀರಾ?",
        "yes": "ಹೌದು",
        "no": "ಇಲ್ಲ",
        "check_farm": "ನನ್ನ ಹೊಲ ಪರಿಶೀಲಿಸಿ",
        "farm_report": "ನಿಮ್ಮ ಹೊಲ ವರದಿ",
        "crop_health_scale": "ಬೆಳೆ ಆರೋಗ್ಯ ಮಟ್ಟ",
        "fully_healthy": "ಸಂಪೂರ್ಣ ಆರೋಗ್ಯಕರ",
        "slight_stress": "ಸ್ವಲ್ಪ ಒತ್ತಡ",
        "moderate_stress": "ಮಧ್ಯಮ ಒತ್ತಡ",
        "high_stress": "ಹೆಚ್ಚಿನ ಒತ್ತಡ",
        "severe_wilted": "ತೀವ್ರ ಒಣಗುವುದು",
        "crop_health": "ಬೆಳೆ ಆರೋಗ್ಯ ಸ್ಥಿತಿ",
        "no_irrigation_now": "ಈಗ ನೀರಾವರಿ ಅಗತ್ಯವಿಲ್ಲ.",
        "irrigation_soon": "ಶೀಘ್ರದಲ್ಲೇ ನೀರಾವರಿ ಮಾಡಿ.",
        "irrigation_now": "ತಕ್ಷಣ ನೀರಾವರಿ ಅಗತ್ಯ!",
        "msg_fully_healthy": "ನಿಮ್ಮ ಬೆಳೆ ಉತ್ತಮ ಸ್ಥಿತಿಯಲ್ಲಿದೆ.",
        "msg_slight_stress": "ಸ್ವಲ್ಪ ಒತ್ತಡ ಇದೆ. ಗಮನಿಸಿ.",
        "msg_moderate_stress": "ಶೀಘ್ರದಲ್ಲೇ ನೀರಾವರಿ ಅಗತ್ಯ.",
        "msg_high_stress": "ತಕ್ಷಣ ನೀರಾವರಿ ಮಾಡಿ.",
        "msg_severe_wilted": "ತಕ್ಷಣ ನೀರಾವರಿ ಅಗತ್ಯ!",
        "safe_delay": "ಸುರಕ್ಷಿತ ವಿಳಂಬ ಎಣಿಕೆ",
        "safe_delay_caption": "ನೀರಾವರಿ ಮಾಡಲು ಮುನ್ನ ಎಷ್ಟು ಕಾಲ ಕಾಯಬಹುದು?",
        "hours": "ಗಂಟೆಗಳು",
        "hours_left": "ಗಂಟೆಗಳು ಉಳಿದಿವೆ",
        "irrigate_now": "ತಕ್ಷಣ ನೀರಾವರಿ ಮಾಡಿ!",
        "irrigate_within": "ಈ ಅವಧಿಯಲ್ಲಿ ನೀರಾವರಿ ಮಾಡಿ",
        "days_safe": "ದಿನಗಳು ಸುರಕ್ಷಿತ",
        "safe_to_wait": "ಕಾಯಬಹುದು",
        "safe_about": "ಸುಮಾರು",
        "days": "ದಿನಗಳು",
        "crop": "ಬೆಳೆ",
        "recent_irrigated": "ಇತ್ತೀಚೆಗೆ ನೀರಾವರಿ ಮಾಡಿದ್ದೀರಾ",
        "safe_delay_desc": "ಹವಾಮಾನ ಮತ್ತು ಬೆಳೆ ಪ್ರಕಾರ ನೀರಿಲ್ಲದೆ ಎಷ್ಟು ಕಾಲ ಇರಬಹುದು ಎಂಬುದನ್ನು ಇದು ತೋರಿಸುತ್ತದೆ.",
        "best_irrigation_time": "ಇಂದು ನೀರಾವರಿಗೆ ಉತ್ತಮ ಸಮಯ",
        "why": "ಏಕೆ?",
        "early_morning_evening": "🌅 ಬೆಳಗ್ಗೆ (5–7 AM) ಅಥವಾ 🌆 ಸಂಜೆ (6–8 PM)",
        "very_hot_reason": "ಇಂದು ತುಂಬಾ ಬಿಸಿ — ಮಧ್ಯಾಹ್ನ ನೀರು ವ್ಯರ್ಥವಾಗುತ್ತದೆ.",
        "avoid_midday": "❌ 10 AM – 4 PM ನಡುವೆ ನೀರಾವರಿ ಬೇಡ",
        "morning_time": "🌅 ಬೆಳಗ್ಗೆ (6–9 AM)",
        "moderate_heat_reason": "ಮಧ್ಯಮ ಬಿಸಿ ಇದೆ. ಬೆಳಿಗ್ಗೆ ನೀರಾವರಿ ಉತ್ತಮ.",
        "avoid_afternoon": "❌ ಇಂದು 2 PM ನಂತರ ನೀರಾವರಿ ಬೇಡ",
        "anytime_morning": "🕐 ಯಾವಾಗ ಬೇಕಾದರೂ — ಬೆಳಿಗ್ಗೆ ಉತ್ತಮ",
        "mild_weather_reason": "ಇಂದು ಹವಾಮಾನ ಮೃದುವಾಗಿದೆ. ಬೆಳಿಗ್ಗೆ ಉತ್ತಮ.",
        "run_motor": "ಮೋಟಾರ್ ಓಡಿಸಿ ಸುಮಾರು",
        "run_drip": "ಡ್ರಿಪ್ ಓಡಿಸಿ ಸುಮಾರು",
        "irrigate_for": "ನೀರಾವರಿ ಮಾಡಿ ಸುಮಾರು",
        "minutes": "ನಿಮಿಷಗಳು",
        "irrigation_risk": "ನೀರಾವರಿ ಅಪಾಯ ಮಟ್ಟ",
        "low_risk": "ಕಡಿಮೆ ಅಪಾಯ",
        "moderate_risk": "ಮಧ್ಯಮ ಅಪಾಯ",
        "high_risk": "ಹೆಚ್ಚಿನ ಅಪಾಯ",
        "very_high_risk": "ಅತ್ಯಧಿಕ ಅಪಾಯ",
        "risk_safe": "ನಿಮ್ಮ ಬೆಳೆ ಸುರಕ್ಷಿತವಾಗಿದೆ.",
        "risk_watch": "ಗಮನಿಸಿ. ಶೀಘ್ರದಲ್ಲೇ ನೀರಾವರಿ ಮಾಡಿ.",
        "risk_plan": "ನೀರಾವರಿ ಅಗತ್ಯವಿದೆ.",
        "risk_now": "ತಕ್ಷಣ ನೀರಾವರಿ ಮಾಡಿ!",
        "very_low": "ತುಂಬಾ ಕಡಿಮೆ",
        "low": "ಕಡಿಮೆ",
        "moderate": "ಮಧ್ಯಮ",
        "high": "ಹೆಚ್ಚು",
        "very_high": "ಅತ್ಯಧಿಕ",
        "rain_forecast_7days": "ಕಳೆದ 7 ದಿನಗಳ ಮಳೆ ಮುನ್ಸೂಚನೆ",
        "rain_caption": "ನಿಮ್ಮ ಹೊಲದ ಸ್ಥಳದ NASA ಮಳೆ ಡೇಟಾ ಆಧಾರಿತ.",
        "no_rain": "ಮಳೆ ಇಲ್ಲ",
        "very_little_rain": "ತುಂಬಾ ಕಡಿಮೆ ಮಳೆ",
        "light_rain": "ಸ್ವಲ್ಪ ಮಳೆ",
        "moderate_rain": "ಮಧ್ಯಮ ಮಳೆ",
        "good_rain": "ಉತ್ತಮ ಮಳೆ",
        "heavy_rain": "ಭಾರಿ ಮಳೆ",
        "rain_good": "ಇತ್ತೀಚೆಗೆ ಉತ್ತಮ ಮಳೆ ಬಂದಿದೆ. ನೀರಾವರಿ ತಡ ಮಾಡಬಹುದು.",
        "rain_some": "ಸ್ವಲ್ಪ ಮಳೆ ಬಂದಿದೆ. ಹೊಲವನ್ನು ಪರಿಶೀಲಿಸಿ.",
        "rain_low": "ಈ ವಾರ ಮಳೆ ಕಡಿಮೆ. ಶೀಘ್ರದಲ್ಲೇ ನೀರಾವರಿ ಮಾಡಿ.",
        "water_stress_trend": "ಕಳೆದ 7 ದಿನಗಳ ನೀರಿನ ಒತ್ತಡ ಧೋರಣೆ",
        "date": "ದಿನಾಂಕ",
        "water_stress_level": "ನೀರಿನ ಒತ್ತಡ ಮಟ್ಟ",
        "welcome_login": "ಸ್ವಾಗತ! ಮುಂದುವರಿಸಲು ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.",
        "mobile_placeholder": "10 ಅಂಕೆಯ ಸಂಖ್ಯೆ",
        "valid_mobile": "ಸರಿಯಾದ 10 ಅಂಕೆಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ.",
        "no_account": "ಖಾತೆ ಇಲ್ಲ. ಹೊಸದು ರಚಿಸಿ →",
        "account_exists": "ಖಾತೆ ಇದೆ. ಲಾಗಿನ್ ಮಾಡಿ.",
        "create_account_title": "ನಿಮ್ಮ ಖಾತೆ ರಚಿಸಿ",
        "new_account_for": "ಹೊಸ ಖಾತೆ:",
        "signup_caption": "ಒಮ್ಮೆ ಭರ್ತಿ ಮಾಡಿ — ಪ್ರತಿ ಲಾಗಿನ್‌ನಲ್ಲಿ ಸ್ವಯಂ ಲೋಡ್ ಆಗುತ್ತದೆ.",
        "your_name": "ನಿಮ್ಮ ಹೆಸರು",
        "name_placeholder": "ಉದಾ: ರಾಮು",
        "your_farms": "ನಿಮ್ಮ ಹೊಲಗಳು",
        "farm_caption": "ನೀವು ಹಲವಾರು ಹೊಲಗಳನ್ನು ಸೇರಿಸಬಹುದು.",
        "how_many_farms": "ನಿಮಗೆ ಎಷ್ಟು ಹೊಲಗಳಿವೆ?",
        "save_start": "ಉಳಿಸಿ ಮತ್ತು ಆರಂಭಿಸಿ →",
        "back_login": "ಲಾಗಿನ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        "enter_place": "ಗ್ರಾಮ, ಮಂಡಲ, ಜಿಲ್ಲೆ ನಮೂದಿಸಿ",
        "place_placeholder": "ಉದಾ: ಅಬೇದೊಡ್ಡಿ, ಜೋಗುಳಾಂಬ ಗದ್ವಾಲ್, ತೆಲಂಗಾಣ",
        "search_location": "ಸ್ಥಳ ಹುಡುಕಿ",
        "location_found": "ಸ್ಥಳ ಕಂಡುಬಂದಿದೆ",
        "try_location_more": "ಮಂಡಲ / ಜಿಲ್ಲೆ / ರಾಜ್ಯ ಸೇರಿಸಿ",
        "final_location": "ಕೊನೆಯ ಹೊಲದ ಸ್ಥಳ",
        "open_google_maps": "Google Maps ನಲ್ಲಿ ಸ್ಥಳ ತೆರೆಯಿರಿ",
        "paste_coordinates": "ನಿಖರ ಹೊಲದ ಸಮನ್ವಯಾಂಕಗಳನ್ನು ನಮೂದಿಸಿ",
        "copy_coordinates_help": "Google Maps → ಹೊಲದ ಮೇಲೆ right click → ಸಮನ್ವಯಾಂಕಗಳನ್ನು ನಕಲಿಸಿ ಇಲ್ಲಿ ಅಂಟಿಸಿ",
        "coord_placeholder": "ಉದಾ: 15.32627, 76.78785",
        "set_coordinates": "ಹೊಲದ ಸಮನ್ವಯಾಂಕಗಳನ್ನು ಹೊಂದಿಸಿ",
        "coordinates_set": "ಹೊಲದ ಸಮನ್ವಯಾಂಕಗಳು ಯಶಸ್ವಿಯಾಗಿ ಹೊಂದಿಸಲಾಗಿದೆ",
        "coord_format": "ಈ ರೀತಿಯಲ್ಲಿ ನಮೂದಿಸಿ: latitude, longitude",
        "edit_profile": "ನನ್ನ ಪ್ರೊಫೈಲ್ ತಿದ್ದುಪಡಿ",
        "save_changes_caption": "Save Changes ಒತ್ತಿದಾಗ ಬದಲಾವಣೆಗಳು ಉಳಿಯುತ್ತವೆ.",
        "name": "ಹೆಸರು",
        "marked_delete": "ಅಳಿಸಲು ಗುರುತಿಸಲಾಗಿದೆ",
        "undo": "ರದ್ದು",
        "keep_one_farm": "ಕನಿಷ್ಠ ಒಂದು ಹೊಲ ಇರಬೇಕು.",
        "add_new_farm": "ಹೊಸ ಹೊಲ ಸೇರಿಸಿ",
        "new_farm_details": "ಹೊಸ ಹೊಲ ವಿವರಗಳು",
        "save_changes": "ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ",
        "back_dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹಿಂತಿರುಗಿ",
        "set_location": "ಹೊಲದ ಸ್ಥಳ ಹೊಂದಿಸಿ",
        "select_crop": "ಬೆಳೆ ಆಯ್ಕೆಮಾಡಿ",
        "water_sources": "ನೀರಿನ ಮೂಲಗಳು",
        "verify_map": "ನಕ್ಷೆ ತೆರೆಯಿರಿ, ಹೊಲ ಪರಿಶೀಲಿಸಿ, ಬೇಕಾದರೆ ಕೆಳಗೆ ಸರಿಪಡಿಸಿ.",
        "delete_farm": "ಈ ಹೊಲವನ್ನು ಅಳಿಸಿ",
        "sign_out": "ಲಾಗ್ ಔಟ್",
        "login": "ಲಾಗಿನ್",
        "create_account": "ಖಾತೆ ರಚಿಸಿ",
        "farmer_advisory_system": "ರೈತ ಸಲಹಾ ವ್ಯವಸ್ಥೆ",
        "crop_label": "ಬೆಳೆ",
        "farm_area": "ಹೊಲದ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)",
        "acres": "ಎಕರೆ"
    },
    "Tamil": {
        "choose_farm": "உங்கள் பண்ணையை தேர்வு செய்யவும்",
        "hello": "வணக்கம்",
        "location": "இடம்",
        "did_irrigate": "சமீபத்தில் நீர்ப்பாசனம் செய்தீர்களா?",
        "yes": "ஆம்",
        "no": "இல்லை",
        "check_farm": "என் பண்ணையை சரிபார்",
        "farm_report": "உங்கள் பண்ணை அறிக்கை",
        "crop_health_scale": "பயிர் ஆரோக்கிய அளவுகோல்",
        "fully_healthy": "முழுமையாக ஆரோக்கியம்",
        "slight_stress": "சிறிய அழுத்தம்",
        "moderate_stress": "மிதமான அழுத்தம்",
        "high_stress": "அதிக அழுத்தம்",
        "severe_wilted": "கடுமையான வாடுதல்",
        "crop_health": "பயிர் ஆரோக்கிய நிலை",
        "no_irrigation_now": "இப்போது நீர்ப்பாசனம் தேவையில்லை.",
        "irrigation_soon": "விரைவில் நீர்ப்பாசனம் பரிந்துரைக்கப்படுகிறது.",
        "irrigation_now": "உடனடி நீர்ப்பாசனம் தேவை!",
        "msg_fully_healthy": "உங்கள் பயிர் சிறந்த நிலையில் உள்ளது.",
        "msg_slight_stress": "சிறிய அழுத்தம். உங்கள் புலத்தை கவனியுங்கள்.",
        "msg_moderate_stress": "விரைவில் நீர்ப்பாசனம் செய்யவும்.",
        "msg_high_stress": "உங்கள் பயிருக்கு விரைவில் நீர் தேவை!",
        "msg_severe_wilted": "உடனடி நீர்ப்பாசனம் அவசியம்!",
        "safe_delay": "பாதுகாப்பான காத்திருப்பு நேரம்",
        "safe_delay_caption": "நீர் ஊற்றுவதற்கு முன் எவ்வளவு நேரம் காத்திருக்கலாம்?",
        "hours": "மணி",
        "hours_left": "மணி மீதம்",
        "irrigate_now": "உடனே நீர்ப்பாசனம் செய்யவும்!",
        "irrigate_within": "இந்த நேரத்திற்குள் நீர்ப்பாசனம் செய்யவும்",
        "days_safe": "நாட்கள் பாதுகாப்பாக காத்திருக்கலாம்",
        "safe_to_wait": "பாதுகாப்பாக காத்திருக்கலாம்",
        "safe_about": "சுமார் பாதுகாப்பானது",
        "days": "நாட்கள்",
        "crop": "பயிர்",
        "recent_irrigated": "சமீபத்தில் நீர்ப்பாசனம் செய்தது",
        "safe_delay_desc": "பயிர் வகை மற்றும் தற்போதைய காலநிலை அடிப்படையில் இந்த நேரம் கணக்கிடப்பட்டது.",
        "best_irrigation_time": "இன்றைய சிறந்த நீர்ப்பாசன நேரம்",
        "why": "ஏன்?",
        "early_morning_evening": "🌅 அதிகாலை (5–7 AM) அல்லது 🌆 மாலை (6–8 PM)",
        "very_hot_reason": "இன்று அதிக வெப்பம் — மதியத்தில் நீர் வீணாகும்.",
        "avoid_midday": "❌ காலை 10 மணி – மாலை 4 மணி தவிர்க்கவும்",
        "morning_time": "🌅 காலை (6–9 AM)",
        "moderate_heat_reason": "மிதமான வெப்பம் எதிர்பார்க்கப்படுகிறது.",
        "avoid_afternoon": "❌ பிற்பகல் 2 மணிக்குப் பிறகு தவிர்க்கவும்",
        "anytime_morning": "🕐 எப்போது வேண்டுமானாலும் — காலை சிறந்தது",
        "mild_weather_reason": "இன்று மிதமான வானிலை.",
        "run_motor": "மோட்டாரை இயக்கவும் சுமார்",
        "run_drip": "டிரிப் பாசனத்தை இயக்கவும் சுமார்",
        "irrigate_for": "நீர்ப்பாசனம் செய்யவும் சுமார்",
        "minutes": "நிமிடங்கள்",
        "irrigation_risk": "நீர்ப்பாசன அபாய நிலை",
        "low_risk": "குறைந்த அபாயம்",
        "moderate_risk": "மிதமான அபாயம்",
        "high_risk": "அதிக அபாயம்",
        "very_high_risk": "மிக அதிக அபாயம்",
        "risk_safe": "உங்கள் பயிர் பாதுகாப்பாக உள்ளது.",
        "risk_watch": "உங்கள் புலத்தை கவனியுங்கள்.",
        "risk_plan": "உங்கள் பயிருக்கு நீர் தேவை.",
        "risk_now": "உடனே நீர்ப்பாசனம் செய்யவும்!",
        "very_low": "மிக குறைவு",
        "low": "குறைவு",
        "moderate": "மிதமான",
        "high": "அதிகம்",
        "very_high": "மிக அதிகம்",
        "rain_forecast_7days": "மழை முன்னறிவிப்பு — கடந்த 7 நாட்கள்",
        "rain_caption": "உங்கள் பண்ணை இடத்தின் NASA மழை தரவு அடிப்படையில்.",
        "no_rain": "மழை இல்லை",
        "very_little_rain": "மிகக் குறைந்த மழை",
        "light_rain": "லேசான மழை",
        "moderate_rain": "மிதமான மழை",
        "good_rain": "நல்ல மழை",
        "heavy_rain": "கனமழை",
        "rain_good": "சமீபத்தில் நல்ல மழை பெய்துள்ளது!",
        "rain_some": "சில மழை கிடைத்துள்ளது.",
        "rain_low": "இந்த வாரம் மழை குறைவு.",
        "water_stress_trend": "நீர் அழுத்த நிலை — கடந்த 7 நாட்கள்",
        "date": "தேதி",
        "water_stress_level": "IDI — நீர் அழுத்த நிலை",
        "welcome_login": "வரவேற்கிறோம்! தொடர உங்கள் மொபைல் எண்ணை உள்ளிடவும்.",
        "mobile_number": "மொபைல் எண்",
        "mobile_placeholder": "10 இலக்க எண்",
        "valid_mobile": "சரியான 10 இலக்க எண்ணை உள்ளிடவும்.",
        "no_account": "கணக்கு இல்லை. தயவுசெய்து உருவாக்கவும் →",
        "account_exists": "கணக்கு உள்ளது. உள்நுழையவும்.",
        "create_account_title": "உங்கள் கணக்கை உருவாக்கவும்",
        "new_account_for": "புதிய கணக்கு:",
        "signup_caption": "ஒருமுறை நிரப்பவும் — அடுத்த முறை தானாக ஏற்றப்படும்.",
        "your_name": "உங்கள் பெயர்",
        "name_placeholder": "உதா: ராமு",
        "your_farms": "உங்கள் பண்ணைகள்",
        "farm_caption": "பல பண்ணைகள் சேர்க்கலாம்.",
        "how_many_farms": "உங்களிடம் எத்தனை பண்ணைகள் உள்ளன?",
        "save_start": "சேமித்து தொடங்கு →",
        "back_login": "உள்நுழைவிற்கு திரும்பு",
        "search_location": "இடத்தை தேடு",
        "final_location": "இறுதி பண்ணை இடம்",
        "open_google_maps": "Google Maps இல் திற",
        "verify_map": "வரைபடத்தை திறந்து பண்ணையை சரிபார்க்கவும்.",
        "set_location": "பண்ணை இடத்தை அமைக்கவும்",
        "select_crop": "பயிரை தேர்வு செய்க",
        "water_sources": "நீர் ஆதாரங்கள்",
        "set_coordinates": "கோஆர்டினேட் அமைக்கவும்",
        "edit_profile": "சுயவிவரம் திருத்து",
        "sign_out": "வெளியேறு",
        "login": "உள்நுழை",
        "create_account": "கணக்கு உருவாக்கு",
        "farmer_advisory_system": "விவசாய ஆலோசனை அமைப்பு",
        "crop_label": "பயிர்",
        "enter_place": "கிராமம், மண்டலம், மாவட்டம் உள்ளிடவும்",
        "name": "பெயர்",
        "save_changes_caption": "Save Changes அழுத்தும்போது மாற்றங்கள் சேமிக்கப்படும்.",
        "paste_coordinates": "துல்லியமான கோஆர்டினேட் ஒட்டவும்",
        "delete_farm": "இந்த பண்ணையை நீக்கு",
        "add_new_farm": "புதிய பண்ணை சேர்க்கவும்",
        "save_changes": "மாற்றங்களை சேமிக்கவும்",
        "back_dashboard": "டாஷ்போர்டுக்கு திரும்பவும்",
        "copy_coordinates_help": "Google Maps → பண்ணையில் right click → கோஆர்டினேட் copy செய்து இங்கே paste செய்யவும்",
        "farm_area": "பண்ணை பரப்பளவு (ஏக்கர்)",
        "acres": "ஏக்கர்"
    },
    "Hindi": {
        "choose_farm": "अपना खेत चुनें",
        "hello": "नमस्ते",
        "location": "स्थान",
        "did_irrigate": "क्या आपने हाल ही में सिंचाई की?",
        "yes": "हाँ",
        "no": "नहीं",
        "check_farm": "मेरा खेत जांचें",
        "farm_report": "आपकी खेत रिपोर्ट",
        "crop_health_scale": "फसल स्वास्थ्य स्तर",
        "fully_healthy": "पूरी तरह स्वस्थ",
        "slight_stress": "हल्का तनाव",
        "moderate_stress": "मध्यम तनाव",
        "high_stress": "अधिक तनाव",
        "severe_wilted": "गंभीर / मुरझाया",
        "crop_health": "फसल स्वास्थ्य स्थिति",
        "no_irrigation_now": "अभी सिंचाई की आवश्यकता नहीं है।",
        "irrigation_soon": "जल्द सिंचाई करने की सलाह है।",
        "irrigation_now": "तुरंत सिंचाई आवश्यक है!",
        "msg_fully_healthy": "आपकी फसल उत्कृष्ट स्थिति में है।",
        "msg_slight_stress": "हल्का तनाव। खेत पर ध्यान रखें।",
        "msg_moderate_stress": "जल्द सिंचाई करें।",
        "msg_high_stress": "आपकी फसल को जल्द पानी चाहिए!",
        "msg_severe_wilted": "तुरंत सिंचाई अत्यावश्यक है!",
        "safe_delay": "सुरक्षित प्रतीक्षा समय",
        "safe_delay_caption": "पानी देने से पहले कितनी देर सुरक्षित प्रतीक्षा कर सकते हैं?",
        "hours": "घंटे",
        "hours_left": "घंटे शेष",
        "irrigate_now": "अभी सिंचाई करें!",
        "irrigate_within": "इसके भीतर सिंचाई करें",
        "days_safe": "दिन सुरक्षित प्रतीक्षा",
        "safe_to_wait": "सुरक्षित प्रतीक्षा",
        "safe_about": "लगभग सुरक्षित",
        "days": "दिन",
        "crop": "फसल",
        "recent_irrigated": "हाल ही में सिंचित",
        "safe_delay_desc": "फसल प्रकार और वर्तमान मौसम के आधार पर यह समय निकाला गया है।",
        "best_irrigation_time": "आज सिंचाई का सबसे अच्छा समय",
        "why": "क्यों?",
        "early_morning_evening": "🌅 सुबह जल्दी (5–7 AM) या 🌆 शाम (6–8 PM)",
        "very_hot_reason": "आज बहुत गर्मी है — दोपहर में पानी व्यर्थ जाएगा।",
        "avoid_midday": "❌ सुबह 10 बजे – शाम 4 बजे से बचें",
        "morning_time": "🌅 सुबह (6–9 AM)",
        "moderate_heat_reason": "मध्यम गर्मी की संभावना है।",
        "avoid_afternoon": "❌ दोपहर 2 बजे के बाद बचें",
        "anytime_morning": "🕐 कभी भी — सुबह बेहतर है",
        "mild_weather_reason": "आज मौसम सामान्य है।",
        "run_motor": "मोटर चलाएँ लगभग",
        "run_drip": "ड्रिप सिंचाई चलाएँ लगभग",
        "irrigate_for": "सिंचाई करें लगभग",
        "minutes": "मिनट",
        "irrigation_risk": "सिंचाई जोखिम स्तर",
        "low_risk": "कम जोखिम",
        "moderate_risk": "मध्यम जोखिम",
        "high_risk": "उच्च जोखिम",
        "very_high_risk": "बहुत अधिक जोखिम",
        "risk_safe": "आपकी फसल सुरक्षित है।",
        "risk_watch": "अपने खेत पर ध्यान रखें।",
        "risk_plan": "आपकी फसल को पानी चाहिए।",
        "risk_now": "तुरंत सिंचाई करें!",
        "very_low": "बहुत कम",
        "low": "कम",
        "moderate": "मध्यम",
        "high": "उच्च",
        "very_high": "बहुत अधिक",
        "rain_forecast_7days": "बारिश पूर्वानुमान — पिछले 7 दिन",
        "rain_caption": "आपके खेत स्थान के NASA वर्षा डेटा पर आधारित।",
        "no_rain": "बारिश नहीं",
        "very_little_rain": "बहुत कम बारिश",
        "light_rain": "हल्की बारिश",
        "moderate_rain": "मध्यम बारिश",
        "good_rain": "अच्छी बारिश",
        "heavy_rain": "भारी बारिश",
        "rain_good": "हाल ही में अच्छी बारिश हुई है!",
        "rain_some": "कुछ बारिश हुई है।",
        "rain_low": "इस सप्ताह बहुत कम बारिश।",
        "water_stress_trend": "जल तनाव प्रवृत्ति — पिछले 7 दिन",
        "date": "तारीख",
        "water_stress_level": "IDI — जल तनाव स्तर",
        "welcome_login": "स्वागत है! जारी रखने के लिए अपना मोबाइल नंबर दर्ज करें।",
        "mobile_number": "मोबाइल नंबर",
        "mobile_placeholder": "10 अंकों का नंबर",
        "valid_mobile": "सही 10 अंकों का नंबर दर्ज करें।",
        "no_account": "कोई खाता नहीं मिला। कृपया बनाएं →",
        "account_exists": "खाता मौजूद है। लॉगिन करें।",
        "create_account_title": "अपना खाता बनाएं",
        "new_account_for": "नया खाता:",
        "signup_caption": "एक बार भरें — अगली बार स्वतः लोड होगा।",
        "your_name": "आपका नाम",
        "name_placeholder": "उदा: रामू",
        "your_farms": "आपके खेत",
        "farm_caption": "आप कई खेत जोड़ सकते हैं।",
        "how_many_farms": "आपके पास कितने खेत हैं?",
        "save_start": "सहेजें और शुरू करें →",
        "back_login": "लॉगिन पर वापस जाएँ",
        "search_location": "स्थान खोजें",
        "final_location": "अंतिम खेत स्थान",
        "open_google_maps": "Google Maps में खोलें",
        "verify_map": "मानचित्र खोलें और खेत जांचें।",
        "set_location": "खेत स्थान सेट करें",
        "select_crop": "फसल चुनें",
        "water_sources": "जल स्रोत",
        "set_coordinates": "निर्देशांक सेट करें",
        "edit_profile": "प्रोफ़ाइल संपादित करें",
        "sign_out": "साइन आउट",
        "login": "लॉगिन",
        "create_account": "खाता बनाएं",
        "farmer_advisory_system": "किसान सलाह प्रणाली",
        "crop_label": "फसल",
        "enter_place": "गाँव, मंडल, जिला दर्ज करें",
        "name": "नाम",
        "save_changes_caption": "Save Changes दबाने पर बदलाव सहेजे जाएंगे।",
        "paste_coordinates": "सटीक निर्देशांक पेस्ट करें",
        "delete_farm": "इस खेत को हटाएँ",
        "add_new_farm": "नया खेत जोड़ें",
        "save_changes": "बदलाव सहेजें",
        "back_dashboard": "डैशबोर्ड पर वापस जाएँ",
        "copy_coordinates_help": "Google Maps → खेत पर राइट क्लिक करें → निर्देशांक कॉपी करें → यहाँ पेस्ट करें",
        "farm_area": "खेत का क्षेत्रफल (एकड़)",
        "acres": "एकड़"
    },
    "Malayalam": {
        "choose_farm": "നിങ്ങളുടെ കൃഷിയിടം തിരഞ്ഞെടുക്കുക",
        "hello": "നമസ്കാരം",
        "location": "സ്ഥലം",
        "did_irrigate": "സമീപകാലത്ത് ജലസേചനം നടത്തിയോ?",
        "yes": "അതെ",
        "no": "ഇല്ല",
        "check_farm": "എന്റെ കൃഷിയിടം പരിശോധിക്കുക",
        "farm_report": "നിങ്ങളുടെ കൃഷിയിട റിപ്പോർട്ട്",
        "crop_health_scale": "വിള ആരോഗ്യ നില",
        "fully_healthy": "മുഴുവൻ ആരോഗ്യം",
        "slight_stress": "ലഘു സമ്മർദ്ദം",
        "moderate_stress": "മിതമായ സമ്മർദ്ദം",
        "high_stress": "കൂടുതൽ സമ്മർദ്ദം",
        "severe_wilted": "ഗുരുതരമായി വാടിയത്",
        "crop_health": "വിളയുടെ ആരോഗ്യ നില",
        "no_irrigation_now": "ഇപ്പോൾ ജലസേചനം ആവശ്യമില്ല.",
        "irrigation_soon": "ഉടൻ ജലസേചനം ശുപാർശ ചെയ്യുന്നു.",
        "irrigation_now": "ഉടൻ ജലസേചനം ആവശ്യമാണ്!",
        "msg_fully_healthy": "നിങ്ങളുടെ വിള മികച്ച നിലയിലാണ്.",
        "msg_slight_stress": "ലഘു സമ്മർദ്ദം. വയൽ ശ്രദ്ധിക്കുക.",
        "msg_moderate_stress": "ഉടൻ ജലസേചനം ചെയ്യുക.",
        "msg_high_stress": "വിളയ്ക്ക് ഉടൻ വെള്ളം ആവശ്യമുണ്ട്!",
        "msg_severe_wilted": "ഉടൻ ജലസേചനം അത്യാവശ്യമാണ്!",
        "safe_delay": "സുരക്ഷിത കാത്തിരിപ്പ് സമയം",
        "safe_delay_caption": "വെള്ളം നൽകുന്നതിന് മുമ്പ് എത്ര സമയം കാത്തിരിക്കാം?",
        "hours": "മണിക്കൂർ",
        "hours_left": "മണിക്കൂർ ബാക്കി",
        "irrigate_now": "ഇപ്പോൾ തന്നെ ജലസേചനം ചെയ്യുക!",
        "irrigate_within": "ഇതിനുള്ളിൽ ജലസേചനം ചെയ്യുക",
        "days_safe": "ദിവസങ്ങൾ സുരക്ഷിതമായി കാത്തിരിക്കാം",
        "safe_to_wait": "കാത്തിരിക്കാം",
        "safe_about": "സുരക്ഷിതമായി ഏകദേശം",
        "days": "ദിവസങ്ങൾ",
        "crop": "വിള",
        "recent_irrigated": "സമീപകാല ജലസേചനം",
        "safe_delay_desc": "വിളയും കാലാവസ്ഥയും അടിസ്ഥാനമാക്കി കണക്കാക്കിയത്.",
        "best_irrigation_time": "ഇന്നത്തെ മികച്ച ജലസേചന സമയം",
        "why": "എന്തുകൊണ്ട്?",
        "early_morning_evening": "🌅 രാവിലെ (5–7 AM) അല്ലെങ്കിൽ 🌆 വൈകുന്നേരം (6–8 PM)",
        "very_hot_reason": "ഇന്ന് വളരെ ചൂടാണ് — ഉച്ചയ്ക്ക് വെള്ളം പാഴാകും.",
        "avoid_midday": "❌ രാവിലെ 10 മുതൽ വൈകുന്നേരം 4 വരെ ഒഴിവാക്കുക",
        "morning_time": "🌅 രാവിലെ (6–9 AM)",
        "moderate_heat_reason": "മിതമായ ചൂട് പ്രതീക്ഷിക്കുന്നു.",
        "avoid_afternoon": "❌ ഉച്ചയ്ക്ക് 2 കഴിഞ്ഞ് ഒഴിവാക്കുക",
        "anytime_morning": "🕐 എപ്പോൾ വേണമെങ്കിലും — രാവിലെ മികച്ചത്",
        "mild_weather_reason": "ഇന്ന് മിതമായ കാലാവസ്ഥ.",
        "run_motor": "മോട്ടോർ പ്രവർത്തിപ്പിക്കുക ഏകദേശം",
        "run_drip": "ഡ്രിപ്പ് ജലസേചനം പ്രവർത്തിപ്പിക്കുക ഏകദേശം",
        "irrigate_for": "ജലസേചനം ചെയ്യുക ഏകദേശം",
        "minutes": "മിനിറ്റ്",
        "irrigation_risk": "ജലസേചന അപകടനില",
        "low_risk": "കുറഞ്ഞ അപകടം",
        "moderate_risk": "മിതമായ അപകടം",
        "high_risk": "ഉയർന്ന അപകടം",
        "very_high_risk": "വളരെ ഉയർന്ന അപകടം",
        "risk_safe": "നിങ്ങളുടെ വിള സുരക്ഷിതമാണ്.",
        "risk_watch": "വയൽ ശ്രദ്ധിക്കുക.",
        "risk_plan": "വിളയ്ക്ക് വെള്ളം ആവശ്യമുണ്ട്.",
        "risk_now": "ഉടൻ ജലസേചനം ചെയ്യുക!",
        "very_low": "വളരെ കുറവ്",
        "low": "കുറവ്",
        "moderate": "മിതമായ",
        "high": "ഉയർന്ന",
        "very_high": "വളരെ ഉയർന്ന",
        "rain_forecast_7days": "മഴ പ്രവചനം — കഴിഞ്ഞ 7 ദിവസം",
        "rain_caption": "NASA മഴ ഡാറ്റ അടിസ്ഥാനമാക്കി.",
        "no_rain": "മഴയില്ല",
        "very_little_rain": "വളരെ കുറവ് മഴ",
        "light_rain": "ലഘു മഴ",
        "moderate_rain": "മിതമായ മഴ",
        "good_rain": "നല്ല മഴ",
        "heavy_rain": "കഠിന മഴ",
        "rain_good": "സമീപകാലത്ത് നല്ല മഴ ലഭിച്ചു!",
        "rain_some": "ചില മഴ ലഭിച്ചു.",
        "rain_low": "ഈ ആഴ്ച മഴ കുറവാണ്.",
        "water_stress_trend": "ജല സമ്മർദ്ദ പ്രവണതി — കഴിഞ്ഞ 7 ദിവസം",
        "date": "തീയതി",
        "water_stress_level": "IDI — ജല സമ്മർദ്ദ നില",
        "welcome_login": "സ്വാഗതം! തുടരാൻ മൊബൈൽ നമ്പർ നൽകുക.",
        "mobile_number": "മൊബൈൽ നമ്പർ",
        "mobile_placeholder": "10 അക്ക നമ്പർ",
        "valid_mobile": "ശരിയായ 10 അക്ക നമ്പർ നൽകുക.",
        "no_account": "അക്കൗണ്ട് കണ്ടെത്തിയില്ല. സൃഷ്ടിക്കുക →",
        "account_exists": "അക്കൗണ്ട് നിലവിലുണ്ട്. ലോഗിൻ ചെയ്യുക.",
        "create_account_title": "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        "new_account_for": "പുതിയ അക്കൗണ്ട്:",
        "signup_caption": "ഒരിക്കൽ പൂരിപ്പിക്കുക — അടുത്ത തവണ സ്വയം ലോഡ് ചെയ്യും.",
        "your_name": "നിങ്ങളുടെ പേര്",
        "name_placeholder": "ഉദാ: രാമു",
        "your_farms": "നിങ്ങളുടെ കൃഷിയിടങ്ങൾ",
        "farm_caption": "ഒന്നിലധികം കൃഷിയിടങ്ങൾ ചേർക്കാം.",
        "how_many_farms": "നിങ്ങൾക്ക് എത്ര കൃഷിയിടങ്ങൾ ഉണ്ട്?",
        "save_start": "സേവ് ചെയ്ത് ആരംഭിക്കുക →",
        "back_login": "ലോഗിനിലേക്ക് മടങ്ങുക",
        "search_location": "സ്ഥലം തിരയുക",
        "final_location": "അവസാന കൃഷിയിട സ്ഥലം",
        "open_google_maps": "Google Maps ൽ തുറക്കുക",
        "verify_map": "മാപ്പ് തുറന്ന് കൃഷിയിടം പരിശോധിക്കുക.",
        "set_location": "കൃഷിയിട സ്ഥലം സജ്ജമാക്കുക",
        "select_crop": "വിള തിരഞ്ഞെടുക്കുക",
        "water_sources": "ജല സ്രോതസുകൾ",
        "set_coordinates": "കോഓർഡിനേറ്റ് സജ്ജമാക്കുക",
        "edit_profile": "പ്രൊഫൈൽ തിരുത്തുക",
        "sign_out": "സൈൻ ഔട്ട്",
        "login": "ലോഗിൻ",
        "create_account": "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
        "farmer_advisory_system": "കർഷക ഉപദേശ സംവിധാനം",
        "crop_label": "വിള",
        "enter_place": "ഗ്രാമം, മണ്ഡലം, ജില്ല നൽകുക",
        "name": "പേര്",
        "save_changes_caption": "Save Changes അമർത്തുമ്പോൾ മാറ്റങ്ങൾ സേവ് ചെയ്യും.",
        "paste_coordinates": "കൃത്യമായ കോഓർഡിനേറ്റ് പകർത്തുക",
        "delete_farm": "ഈ കൃഷിയിടം നീക്കുക",
        "add_new_farm": "പുതിയ കൃഷിയിടം ചേർക്കുക",
        "save_changes": "മാറ്റങ്ങൾ സേവ് ചെയ്യുക",
        "back_dashboard": "ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക",
        "copy_coordinates_help": "Google Maps → വയലിൽ right click → കോഓർഡിനേറ്റ് copy ചെയ്ത് ഇവിടെ paste ചെയ്യുക",
        "farm_area": "കൃഷിയിട വിസ്തീർണം (ഏക്കർ)",
        "acres": "ഏക്കർ"
    }
}
CROP_LABELS = {
    "English": {
        "Rice": "Rice",
        "Cotton": "Cotton",
        "Groundnut": "Groundnut",
        "Ragi": "Ragi",
        "Sugarcane": "Sugarcane"
    },
    "Telugu": {
        "Rice": "వరి",
        "Cotton": "పత్తి",
        "Groundnut": "వేరుశెనగ",
        "Ragi": "రాగి",
        "Sugarcane": "చెరకు"
    },
    "Kannada": {
        "Rice": "ಅಕ್ಕಿ",
        "Cotton": "ಹತ್ತಿ",
        "Groundnut": "ಕಡಲೆಕಾಯಿ",
        "Ragi": "ರಾಗಿ",
        "Sugarcane": "ಕಬ್ಬು"
    },
    "Tamil": {
        "Rice": "அரிசி",
        "Cotton": "பருத்தி",
        "Groundnut": "வேர்க்கடலை",
        "Ragi": "ராகி",
        "Sugarcane": "கரும்பு"
    },
    "Hindi": {
        "Rice": "चावल",
        "Cotton": "कपास",
        "Groundnut": "मूंगफली",
        "Ragi": "रागी",
        "Sugarcane": "गन्ना"
    },
    "Malayalam": {
        "Rice": "അരി",
        "Cotton": "പട്ടു",
        "Groundnut": "വേരുശെനഗ",
        "Ragi": "രാഗി",
        "Sugarcane": "ചെരുപ്പ്"
    }
}
SOURCE_LABELS = {
    "English": {
        "Rain": "Rain",
        "Borewell": "Borewell",
        "Motor": "Motor",
        "Canal": "Canal",
        "Drip": "Drip"
    },
    "Telugu": {
        "Rain": "వర్షం",
        "Borewell": "బోర్‌వెల్",
        "Motor": "మోటార్",
        "Canal": "కాలువ",
        "Drip": "డ్రిప్"
    },
    "Kannada": {
        "Rain": "ಮಳೆ",
        "Borewell": "ಬೋರ್‌ವೆಲ್",
        "Motor": "ಮೋಟಾರ್",
        "Canal": "ಕಾಲುವೆ",
        "Drip": "ಡ್ರಿಪ್"
    },
    "Tamil": {
        "Rain": "மழை",
        "Borewell": "போர்வெல்",
        "Motor": "மோட்டார்",
        "Canal": "கால்வாய்",
        "Drip": "டிரிப்"
    },
    "Hindi": {
        "Rain": "बारिश",
        "Borewell": "बोरवेल",
        "Motor": "मोटर",
        "Canal": "कैनल",
        "Drip": "ड्रिप"
    },
    "Malayalam": {
        "Rain": "മഴ",
        "Borewell": "ബോർവെൽ",
        "Motor": "മോട്ടോർ",
        "Canal": "കനാൽ",
        "Drip": "ഡ്രിപ്പ്"
    }
}